lhv.reserve.iban: EE327700771002504613
lhv.gateway.iban: EE697700771002504626

lhv:
  connect.keyStore:
    URL: file:./lhv.jks
    password: letmein
    
database: 
  url: jdbc:postgresql://localhost:5432/gateway
  username: lhv_gateway
  password:
  schema: lhv

slack.webhook.reserve.url: https://hooks.slack.com/services/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

---
spring:
  profiles: dev
database:
  url: jdbc:postgresql://localhost:54321/gateway
  username: gateway
  password:
  schema:
