bank.lhv:
  url: https://www.lhv.ee
  loginPath: /auth/login.cfm
  username: <here>
  password: <here>

lhv.reserve.iban: EE_TODO_TODO_TODO

lhv.connect.keyStore.path: 
lhv.connect.keyStore.password: 
    
database: 
  url: jdbc:postgresql://postgres.cxey7gwcsm2l.eu-west-1.rds.amazonaws.com:5432/gateway
  username: lhv_gateway
  password: 
  schema: lhv
