version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: cache-{{ checksum "build.gradle" }}

      - run: gradle test

      - run: gradle build

      - run:
          command: |
            mkdir -p /tmp/jar
            cp build/libs/*.jar /tmp/jar

      - store_artifacts:
          path: /tmp/jar
          destination: jar