defaults: &defaults
  working_directory: ~/build
  docker:
    - image: circleci/java:8-jdk

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: cache-{{ checksum "build.gradle" }}

      - run: gradle test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}
      - run: gradle publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master